(ns cases.core.k.keyword?)

;; Return true if x is a Keyword
(println "(keyword? 'x)" (keyword? 'x))
(println "(keyword? :x)" (keyword? :x))
(println "(keyword? true)" (keyword? true))
(println "(keyword? :-)" (keyword? :-))
(println "(keyword? :+)" (keyword? :+))
(println "(keyword? :-o)" (keyword? :-o))
(println "(keyword? :')" (keyword? :'))
(println "(keyword? :#)" (keyword? :#))
(println "(keyword? :</>)" (keyword? :</>))
(println "(keyword? :'/-)" (keyword? :'/-))
(println "(keyword? :-:-)" (keyword? :-:-))
(println "(keyword? :....)" (keyword? :....))
(println "(keyword? :73)" (keyword? :73))
(println "(keyword? :a:b:c)" (keyword? :a:b:c))
(println "(keyword? :a.b.c)" (keyword? :a.b.c))
;(keyword? :'//-)
;(keyword? :////)
;(keyword? :'//-,)
;(keyword? :'//,-)
;(keyword? :'// -)
;(keyword? :    )
;(keyword? :-:)
;(keyword? :,,,,)
